# Generated by Django 2.0.2 on 2018-09-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180930_1535'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserHouse')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
            ],
        ),
    ]
