# Generated by Django 2.0.2 on 2018-09-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_auto_20180930_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(default='Working Condition', max_length=30)),
                ('cammodel', models.CharField(default='IP Camera', max_length=10)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserHouse')),
            ],
        ),
        migrations.CreateModel(
            name='SensorAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(default='Working Condition', max_length=30)),
                ('alramtype', models.CharField(default='PIR Sensors', max_length=10)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserHouse')),
            ],
        ),
    ]
