# Generated by Django 2.0.2 on 2018-09-30 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserHouse'),
        ),
        migrations.AlterField(
            model_name='sensoralarm',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserHouse'),
        ),
    ]
