# Generated by Django 2.0.2 on 2018-10-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0003_auto_20180930_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensoralarm',
            old_name='alramtype',
            new_name='alarmtype',
        ),
    ]
