# Generated by Django 2.0.2 on 2018-10-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0004_auto_20181002_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='condition',
            field=models.TextField(default='Not Installed', max_length=30),
        ),
        migrations.AlterField(
            model_name='sensoralarm',
            name='condition',
            field=models.TextField(default='Not Installed', max_length=30),
        ),
    ]
